SystemAdmin 
d8f71ad6-01c6-4142-aeb7-ca7fafc6ae0d.SubscriptionUser 
d8f71ad6-01c6-4142-aeb7-ca7fafc6ae0d.SubscriptionAdmin 
7ace7c14-f317-4def-8370-a7c0351ca04b.SubscriptionUser


https://localhost:7291/subscriptions/sub1/AdminsPolicy
https://localhost:7291/subscriptions/sub2/AdminsPolicy

https://localhost:7291/subscriptions/sub1/Admins
https://localhost:7291/subscriptions/sub2/Admins

https://localhost:7291/subscriptions/sub1/SubAdminsPolicy
https://localhost:7291/subscriptions/sub2/SubAdminsPolicy

https://localhost:7291/subscriptions/sub1/SubAdmins
https://localhost:7291/subscriptions/sub2/SubAdmins


https://localhost:7291/subscriptions/sub1/SubUsersPolicy
https://localhost:7291/subscriptions/sub2/SubUsersPolicy

https://localhost:7291/subscriptions/sub1/SubUsers
https://localhost:7291/subscriptions/sub2/SubUsers

https://localhost:7291/subscriptions/sub1/SuperAdminPolicy
https://localhost:7291/subscriptions/sub2/SuperAdminPolicy

https://localhost:7291/subscriptions/sub1/SuperAdmin
https://localhost:7291/subscriptions/sub2/SuperAdmin

