on:
  pull_request:
    branches:
      - main
    paths:
      - "src/Saas.Provider/**"
      - ".github/**"


name: Build PR and Deploy to new Slot

jobs:
  build-and-deploy:
    # Utilizes re-usable template to build and deploy to app service slot
    uses: Azure/azure-saas/.github/workflows/pr-deploy.yml@main
    with:
      dotnet_version: '5.0.x'
      artifact_name: "${{ env.GITHUB_REF_NAME }}-${{ env.GITHUB_RUN_ID }}"
      slot_name: ${{ env.GITHUB_REF_NAME }}
      app_service_name: app-asdk-dev-001
      app_service_resource_group_name: azure-saas-dev
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}