on:
  pull_request:
    branches:
      - main
    paths:
      - "src/Saas.Provider/**"
      - ".github/**"


name: Saas.Provider.Web PR Build

jobs:
  build-and-deploy:
    # Utilizes re-usable template to build and deploy to app service slot
    uses: Azure/azure-saas/.github/workflows/template-pr-deploy.yml@users/landonpierce/devenv
    with:
      dotnet_version: '5.0.x'
      artifact_name: ${{ format('{0}-{1}', github.ref_name, github.run_id) }} 
      slot_name: ${{ github.ref_name }}
      app_service_name: app-asdk-dev-001
      app_service_resource_group_name: azure-saas-dev
      project_build_path: src/Saas.Admin/Saas.Provider.sln      
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}