on:
  workflow_call:
    secrets:
      WEBHOOK_URL:
        required: true

name: Container Image Publishing - Webhook

jobs:
  webhook:
    # Issues a POST against a provided webhook url to trigger a container update
    runs-on: ubuntu-latest
    steps:
    - name: Issue Webhook Message
      id: request
      uses: fjogeleit/http-request-action@v1
      with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: 'POST'
    - name: Show Response
      run: |
        echo "Response:"
        echo ${{ steps.request.outputs.response }}